name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  shared-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false

      - name: Assemble Shared
        run: ./gradlew :shared:assembleDebug --no-daemon

      - name: Run Shared lints
        run: |
          ./gradlew :shared:lintDebug --no-daemon
          ./gradlew :shared:lintKotlin --no-daemon

      - name: Run Shared unit tests
        run: ./gradlew :shared:testDebugUnitTest --no-daemon

  android-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false

      - name: Assemble Android app
        run: ./gradlew :androidApp:assembleDebug --no-daemon

      - name: Run Android lints
        run: |
          ./gradlew :androidApp:lintDebug --no-daemon
          ./gradlew :androidApp:lintKotlin --no-daemon

      - name: Run Android unit tests
        run: ./gradlew :androidApp:testDebugUnitTest --no-daemon

      - name: Run Android instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          script: ./gradlew :androidApp:connectedCheck --no-daemon

  ios-checks:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false

      - name: Build iOS app
        run: ./gradlew :iosApp:build --no-daemon

      - name: Run iOS lints
        run: ./gradlew :iosApp:lintSwift --no-daemon

      - name: Run iOS UI tests
        run: ./gradlew :iosApp:uiTest --no-daemon
